# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "https://ishitamukhopadhyay.github.io"
baseurl: ""

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: My website

# Short description of your site
description: A virtual proof that name is awesome!

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  About Me: "https://ishitamukhopadhyay.github.io"
  Resources:
    - Beautiful Jekyll: "https://ishitamukhopadhyay.github.io"
  Author's home: "https://ishitamukhopadhyay.github.io"
